# Generated by Django 2.2.24 on 2021-06-22 08:29

from django.db import migrations, models
import gitmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmanager', '0002_courserepo_sphinx_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseupdate',
            name='updated',
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='status',
            field=models.CharField(choices=[(gitmanager.models.UpdateStatus('PENDING'), 'PENDING'), (gitmanager.models.UpdateStatus('RUNNING'), 'RUNNING'), (gitmanager.models.UpdateStatus('SUCCESS'), 'SUCCESS'), (gitmanager.models.UpdateStatus('FAILED'), 'FAILED'), (gitmanager.models.UpdateStatus('SKIPPED'), 'SKIPPED')], default=gitmanager.models.UpdateStatus('PENDING'), max_length=10),
        ),
    ]
