# Generated by Django 2.2.24 on 2021-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmanager', '0004_auto_20210622_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseupdate',
            name='log',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
