# Generated by Django 2.2.24 on 2021-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmanager', '0005_auto_20210622_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserepo',
            name='sphinx_version',
        ),
    ]
