# Generated by Django 2.2.24 on 2021-06-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmanager', '0006_remove_courserepo_sphinx_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRepo',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='courseupdate',
            old_name='course_repo',
            new_name='course',
        ),
    ]
