#!/bin/sh

ver=${DOCKER_TAG##*-}
if [ "$ver" -a "$ver" = "$DOCKER_TAG" ]; then
    ver="$DOCKER_TAG"
fi

for layer in "" "huey"; do
    if [ "$layer" ]; then
        tag="${layer}-${ver}"
    else
        tag="$ver"
    fi
    docker push "$DOCKER_REPO":"$tag"
done

