#!/bin/sh

. /usr/local/lib/cont-init-functions.sh
ENSURE_DIR_MODE=2755
ENSURE_DIR_USER=gitmanager
ENSURE_DIR_GROUP=nogroup

ensure_dir /run/gitmanager
ensure_dir /local/gitmanager
ensure_dir /local/gitmanagerhuey
ensure_dir /local/gitmanager/static
ensure_dir /local/gitmanager/media

# Ensure group permissions
sock=/var/run/docker.sock
gid=$(stat -c '%g' $sock)
gname=$(getent group "$gid")
[ "$gname" ] || groupadd -g "$gid" docker_socket
usermod -G "$gid" gitmanager

# Ensure gitmanager access to /tmp/aplus
chmod 1777 /tmp/aplus
