# Generated by Django 2.2.24 on 2021-06-22 08:29

from django.db import migrations, models
import builder.models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_courserepo_sphinx_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseupdate',
            name='updated',
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='status',
            field=models.CharField(choices=[(builder.models.UpdateStatus('PENDING'), 'PENDING'), (builder.models.UpdateStatus('RUNNING'), 'RUNNING'), (builder.models.UpdateStatus('SUCCESS'), 'SUCCESS'), (builder.models.UpdateStatus('FAILED'), 'FAILED'), (builder.models.UpdateStatus('SKIPPED'), 'SKIPPED')], default=builder.models.UpdateStatus('PENDING'), max_length=10),
        ),
    ]
