# Generated by Django 2.2.24 on 2021-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20210622_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseupdate',
            name='updated_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
