# Generated by Django 2.2.24 on 2021-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_course_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email_on_error',
            field=models.BooleanField(default=True),
        ),
    ]
