# Generated by Django 2.2.25 on 2022-01-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_course_update_automatically'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='courseupdate',
            options={'ordering': ['-request_time']},
        ),
    ]
