# Generated by Django 2.2.26 on 2022-01-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_course_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseupdate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=10),
        ),
    ]
