# Generated by Django 3.2.13 on 2022-08-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_auto_20220127_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skip_build_failsafes',
            field=models.BooleanField(default=False),
        ),
    ]
